openai-service:
  api-key: ${API_KEY}
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: ${READ_TIMEOUT}
    connect-timeout: ${CONNECT_TIMEOUT}
  urls:
    base-url: ${BASE_URL}
    chat-url: ${CHAT_URL}
    create-transcription-url: ${AUDIO_URL}